### ISSUE TITLE
Accuracy observations

### ISSUE THREAD

**Issue by namarsha** [namarsha/MotherSignificantFeatureProject#3]
Hi Matt, in your last message to the team concerning the code you said you weren't getting good accuracy with your models. As I'm reading through the code we're actually getting really high accuracy, but the concern for me is that, according to the last confusion matrix, in a batch of 60 samples, 59 were non-hypertensive. Why is our batch so imbalanced, given the explicit SMOTE-ing earlier in the code? Does anyone watching this repo have any ideas?

**Comment by mattrusso22** [comment]
The accuracy is trivial due to the imbalance of the data. Sure it's high but it's not reliable and you can see that in the confusion matrix. I'm not sure why the data did not improve (at least a little) after using SMOTE.

**Comment by namarsha** [comment]
To answer my own question above: The test set is imbalanced because we (rightfully) split the data before smoting, leaving the test data imbalanced.

What if we trained the model on fewer instances, thus allowing for a larger test set with a greater possibility of hypertensive disorder.

**Comment by mattrusso22** [comment]
We can try - what are you thinking for test size

**Comment by mattrusso22** [comment]
I tried... still imbalanced
